name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed for GITHUB_TOKEN to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR using GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract tag or fallback to latest
        id: meta
        run: |
          TAG=${GITHUB_REF##*/}
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            TAG=latest
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.meta.outputs.tag }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.meta.outputs.tag }}